pipeline {
    agent any
    tools {
        maven 'Maven3'
    }
    stages {
        stage('Compilar') {
            steps {
                bat 'cd demo && mvn clean install -DskipTests'
            }
        }
        stage('Pruebas de Integración') {
            steps {
                bat 'cd demo && mvn test'
            }
        }
    }
}
